settings:
  WINDOW_TITLE: "aimlab_tb"
  roi_width: 680
  roi_height: 680
  debug: true
  control_mose: true
  fire_switch: 1  # 0 為邊緣打擊，1 為中心打擊
  fire_k: 10
  #yolo_model_path: "C:\\Users\\User\\Downloads\\Compressed\\Yolo_Aimlab-main\\Yolo_Aimlab-main\\detect\\train\\weights\\best.pt" # YOLOv5 模型路徑
  yolo_model_path: "C:\\Users\\User\\yolov5\\runs\\train\\exp3\\weights\\best.pt" # YOLOv5 模型路徑
  mouse_smoothing: 0.1 # 滑鼠移動平滑係數 (0.1-1.0)，值越小移動越平滑
  pid_kp: 0.5 # PID 比例增益
  pid_ki: 0.0 # PID 積分增益
  pid_kd: 0 # PID 微分增益
  pid_smooth: 0.8 # PID 輸出整體平滑因子
  target_stickiness: 0.2 # (0-1.0) 數值越低越「黏」。防止準心抖動。

logging:
  level: "INFO"

device:
  path: "devices/MouseControl.dll"