settings:
  WINDOW_TITLE: "aimlab_tb"
  roi_width: 680
  roi_height: 680
  debug: false
  debug_window_scale: 0.25 # 除錯視窗縮放比例
  control_mose: true
  enable_auto_fire: true # 是否啟用自動開火 (true/false)
  fire_mode: 0           # 開火模式 (0: 當準星進入目標偵測框內, 1: 當準星靠近目標中心一定範圍內)
  #yolo_model_path: "C:\\Users\\User\\Downloads\\Compressed\\Yolo_Aimlab-main\\Yolo_Aimlab-main\\detect\\train\\weights\\best.pt" # YOLOv5 模型路徑
  yolo_model_path: "C:\\Users\\User\\yolov5\\runs\\train\\exp3\\weights\\best.pt" # YOLOv5 模型路徑
  mouse_smoothing: 0.1 # 滑鼠移動平滑係數 (0.1-1.0)，值越小移動越平滑
  pid_kp: 0.3 # PID 比例增益
  pid_ki: 0.0 # PID 積分增益
  pid_kd: 0 # PID 微分增益
  pid_smooth: 0.6 # PID 輸出整體平滑因子
  target_stickiness: 0.1 # (0-1.0) 數值越低越「黏」。防止準心抖動。

logging:
  level: "INFO"

device:
  path: "devices/MouseControl.dll"