device:
  path: devices/MouseControl.dll
hotkeys:
  exit_key: end
  pause_key: p
logging:
  level: INFO
settings:
  WINDOW_TITLE: aimlab_tb
  control_mose: true
  debug: true
  debug_window_scale: 0.25
  enable_auto_fire: true
  fire_mode: 0
  mouse_smoothing: 0.1
  pid_kd: 0.1
  pid_ki: 0.05
  pid_kp: 0.1
  pid_smooth: 0.7
  roi_height: 680
  roi_width: 680
  target_stickiness: 0.1
  yolo_model_path: weights/weights/best.pt
